### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by xaviershay** [factorio-item-browser/export#17]
Hello, I'm working on a project for designing factory layouts (basically a port of Foreman to the web) and I was hoping to see if I could re-use some of the excellent work you've done here. I'm totally new to PHP, and struggling a bit to find the right entry point to this project. The `Makefile` doesn't appear to have a target for actually generating a dump of the data. I'm also a bit confused as to what goes in docker vs what doesn't, e.g. `make test` fails with `phpunit` not found, but I would have expected that to be in the container.

Do you have instructions written up anywhere? Thanks!

**Comment by BluePsyduck** [comment]
Hi Xavier,

the reason there are no real instructions on how to run this project is because it is not meant to be run for  tools other than the Factorio Item Browser (FIB) itself. It is tightly coupled to its infrastructure and data layout, and pushes the exported data directly to the API server. 

You said you want to create some kind of web-version of Foreman. Therefor I think you may be more interested in the API of the FIB, which provides the data exported from the game in JSON data structures. The API has an [Open-API specification](https://petstore.swagger.io/?url=https://raw.githubusercontent.com/factorio-item-browser/api-server/master/api/openapi.yaml) as documentation. (While the new API server is already up and running at api.factorio-item-browser.com, it only contains data for Vanilla for now, because the new web frontend is not fully ready yet.)

If you are on the Factorio Discord server, feel free to contact me there (nickname "BluePsyduck" as well) and we can discuss in more detail what you can use from the FIB project etc. ;)

**Comment by xaviershay** [comment]
legend, exactly what I was after, will hit you up on discord

https://github.com/xaviershay/factorio-layout-designer is the project fwiw
